CREATE DATABASE Hogwarts;
USE Hogwarts;

CREATE TABLE Feitico(
idFeitico INT PRIMARY KEY AUTO_INCREMENT,
nome VARCHAR(45) NOT NULL,
tipo VARCHAR(45) NOT NULL,
efeito VARCHAR(45) NOT NULL,
dano INT
);

CREATE TABLE Bruxo(
idBruxo INT PRIMARY KEY AUTO_INCREMENT,
nome VARCHAR(45) NOT NULL,
idade INT NOT NULL,
ano INT NOT NULL
);

CREATE TABLE Vassoura(
idVassoura INT PRIMARY KEY AUTO_INCREMENT,
velocidade INT NOT NULL,
resistencia INT NOT NULL,
conforto INT,
estabilidade INT NOT NULL
);

CREATE TABLE Casa(
idCasa INT PRIMARY KEY AUTO_INCREMENT,
nome VARCHAR(45) NOT NULL,
fundador VARCHAR(45) NOT NULL,
mascote VARCHAR(45) NOT NULL,
elemento VARCHAR(45) NOT NULL
);

CREATE TABLE Varinha(
idVarinha INT PRIMARY KEY AUTO_INCREMENT,
nucleo VARCHAR(45) NOT NULL,
madeira VARCHAR(45) NOT NULL
);

CREATE TABLE Materia(
idMateria INT PRIMARY KEY AUTO_INCREMENT,
nome VARCHAR(45) NOT NULL,
professor VARCHAR(45) NOT NULL
);